---
# tasks file for ansible-role-system
#- name: Allow sudo without password
#  become: yes
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
#    insertafter: '^%admin\tALL=\(ALL\) ALL'
#    validate: "visudo -cf %s"
#  when: sudo_without_password and ansible_os_family == "Darwin"

- name: Check if original hosts backup file exists
  stat:
    path: "{{ hosts_backup }}"
  register: stat_result

- name: Backup original hosts file
  become: yes
  copy:
    src: "{{ hosts_path }}"
    dest: "{{ hosts_backup }}"
    force: yes
  when: not stat_result.stat.exists and not hosts_pack == "none"

- name: Restore original hosts file
  become: yes
  copy:
    src: "{{ hosts_backup }}"
    dest: "{{ hosts_path }}"
  when: stat_result.stat.exists and hosts_pack == "none"

- name: Delete backup of original hosts file
  become: yes
  file:
    path: "{{ hosts_backup }}"
    state: absent
  when: stat_result.stat.exists and hosts_pack == "none"

- name: Set hosts file
  become: yes
  get_url:
    force: yes
    url: "{{ hosts_url }}"
    dest: "{{ hosts_path }}"
    group: root
    owner: root
  when: not hosts_pack == "none"

- name: copy udev rule for ergoxox keyboard
  become: yes
  copy:
    src: "{{ role_path }}/files/50-wally.rules"
    dest: /etc/udev/rules.d/50-wally.rules
    owner: root
    group: root

- name: Add plugdev group
  group:
    name: plugdev
    state: present

- name: adding existing "{{ user }}" to group plugdev
  user:
    name: "{{ user }}"
    groups: plugdev
    append: yes

- include_tasks: thinkpad.yml
  when: thinkpad == true
