---
# tasks file for ansible-role-system
- name: Allow sudo without password
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
    insertafter: '^%admin\tALL=\(ALL\) ALL'
    validate: "visudo -cf %s"
  when: sudo_without_password|default(false) == true

- name: Set Caps as additional ESC key
  become: yes
  lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBOPTIONS="
    line: XKBOPTIONS="caps:escape"

- include_tasks: thinkpad.yml
  when: thinkpad|default(false) == true

- include_tasks: hosts.yml
  when: hosts_pack|default(false) != "none"
