- name: copy trackpoint conf
  copy:
    src: "{{ role_path }}/files/20-trackpoint.conf"
    dest: /etc/X11/xorg.conf.d/20-trackpoint.conf
    owner: root
    group: root

- name: trackpoint sleep workaround 2
  modprobe:
    name: psmouse
    params: synaptics_intertouch=1
    state: present

- name: persist trackpoint sleep workaround
  copy:
    src: "{{ role_path }}/files/psmouse"
    dest: /etc/modprobe.d/psmouse.conf
    owner: root
    group: root
